<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Wheel Macro -->
    <xacro:macro name="wheel" params="prefix side">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 ${side * wheel_offset_y} ${wheel_radius*(-15/14)}" rpy="${-side * pi/2} 0 0"/>
            <axis xyz="0 0 ${side}"/>
        </joint>
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 1.0"/> <!-- White color for the wheel -->
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 1.0"/> <!-- White color for the wheel -->
                </material>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <!-- Base Footprint -->
    <link name="base_footprint"/>

    <!-- Chassis -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0"/>
    </joint>
    <link name="base_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_length/2}" length="${chassis_height+pole_height+chassis_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${chassis_length/2}" length="${chassis_height+pole_height+chassis_height}"/>
            </geometry>
            <material name="black">
                <color rgba="0.1 0.1 0.1 1.0"/>
            </material>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_height+pole_height+chassis_height}" radius="${chassis_length/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- Wheels -->
    <xacro:wheel prefix="left" side="1"/>
    <xacro:wheel prefix="right" side="-1"/>

     <!-- Front Caster Wheel -->
    <joint name="front_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_caster"/>
        <origin xyz="${chassis_length/2 - 0.03} 0 ${-(caster_sphere_radius/2)-((chassis_height+pole_height+chassis_height)/2)}"/>
    </joint>
    <link name="front_caster">
        <visual>
            <geometry>
                <sphere radius="${caster_sphere_radius/2}"/>
            </geometry>
            <material name="white">
                <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_sphere_radius/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_sphere_radius/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    <gazebo reference="front_caster">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- Rear Caster Wheel -->
    <joint name="rear_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="rear_caster"/>
        <origin xyz="${-chassis_length/2 + 0.03} 0 ${-(caster_sphere_radius/2)-((chassis_height+pole_height+chassis_height)/2)}"/>
    </joint>
    <link name="rear_caster">
        <visual>
            <geometry>
                <sphere radius="${caster_sphere_radius/2}"/>
            </geometry>
            <material name="white">
                <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_sphere_radius/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_sphere_radius/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    <gazebo reference="rear_caster">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>